apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: manis1
  name: manis1
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: manipod1
  type: NodePort
status:
  loadBalancer: {}
