apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podx1
  name: podx1
spec:
  containers:
  - image: dockerashu/ciscohttp:ashuv1
    name: pod1x
    ports:
    - containerPort: 80
    env:
    - name: web   #  name of variable from Dockerfile 
      value: app2   #  it is similar  docker run -e  web=app1  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
