apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podx
  name: podx
spec:
  containers:
  - image: dockerashu/ciscohttp:ashuv1
    name: podx
    ports:
    - containerPort: 80
    env:
    - name: web   #  name of variable from Dockerfile 
      valueFrom:  #  it is similar  docker run -e  web=app1  
       configMapKeyRef:
        name: manicm1   # name of configmap
        key: x     #  name of key where value is stored 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
